version: '3.7'

services:

  nginx:
    build: ./images/nginx
    container_name: ng01
    ports:
      - "80:80"
    depends_on:
      - app
    network_mode: host

  app:
    build:
      dockerfile: ./images/app/Dockerfile
      context: .
    environment:
      - APP_ENV=development
      - GEOIP_S3_BUCKET=pocket-geoip
    ports:
      - "8000:8000"
    volumes:
      - "./:/app"
    network_mode: host
    depends_on:
      - s3

  s3:
    image: pocket/fake-s3:20190604
    ports:
    - "4569:4569"
    network_mode: host
    volumes:
      - "fake_s3_vol:/fakes3/data"

volumes:
  fake_s3_vol:
