version: '3.7'

services:
  nginx:
    build: images/nginx
    container_name: ng01
    ports:
      - "80:80"

    depends_on:
      - app

  app:
    build:
      dockerfile: images/app/Dockerfile
      context: .
      args:
        UID: ${UID:-10001}
        GID: ${GID:-10001}

    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      - APP_ENV=development
      - GEOIP_S3_BUCKET=pocket-geoip
      - ADZERK_API_KEY=${ADZERK_API_KEY}
      - ADZERK_NETWORK_ID=10250
      - SENTRY_DSN=${SENTRY_DSN}

    ports:
      - 8000:8000

    volumes:
      - .:/app:ro
      - .:/opt/project/src:ro

    depends_on:
      - s3

  s3:
    image: pocket/fake-s3:20190604
    ports:
      - "4569:4569"

    volumes:
      - "fake_s3_vol:/fakes3/data"

volumes:
  fake_s3_vol: {}
