AWSTemplateFormatVersion: 2010-09-09
Description: Proxy server service - privacy layer to front ad related vendors.
Parameters:
  EcsNginxRepositoryName:
    Type: String
    Default: nginx

  EcsNginxGitSHA:
    Type: String
    Description: The sha to use
    Default: latest

  EcsProxyRepositoryName:
    Type: String
    Default: proxy

  EcsProxyGitSHA:
    Type: String
    Description: The sha to use
    Default: latest

  EcsTaskMemory:
    Type: String
    Default: 2GB

  EcsTaskCpu:
    Type: String
    Default: 1024

  EcsServiceTaskDesiredCount:
    Type: String
    Default: 115

  EcsServiceTaskMaxCount:
    Type: String
    Default: 250

  EcsServiceTaskMinCount:
    Type: String
    Default: 50

  EcsScaleTaskUpCount:
    Type: String
    Default: 9

  EcsScaleTaskDownCount:
    Type: String
    Default: -6

  EcsScaleTaskUpCooldown:
    Type: String
    Default: 60

  EcsScaleTaskDownCooldown:
    Type: String
    Default: 300

  EcsAppEnv:
    Type: String
    Default: production

  EcsAppGeoipS3Bucket:
    Type: String
    Default: pocket-proxy-geoip

  EcsAppAdzerkSecretName:
    Type: String
    Default: prod/adzerk

  EcsAppSentryDsnSecretName:
    Type: String
    Default: prod/sentry_dsn

  ServiceScaleEvaluationPeriods:
    Description: "The number of periods over which data is compared to the specified threshold"
    Type: Number
    Default: 2
    MinValue: 2

  ServiceCpuScaleUpThreshold:
    Type: Number
    Description: "Average CPU value to trigger auto scaling up"
    Default: 55
    MinValue: 0
    MaxValue: 100
    ConstraintDescription: Value must be between 0 and 100

  ServiceCpuScaleDownThreshold:
    Type: Number
    Description: "Average CPU value to trigger auto scaling down"
    Default: 44
    MinValue: 0
    MaxValue: 100
    ConstraintDescription: Value must be between 0 and 100

  SSLCertificateArn:
    Type: String
    Description: Certificate ARN for ALB listener

  VPCStackName:
    Type: String
    Description: Stack name of VPC
    Default: VPC

Resources:
  Alb:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: !Ref "AWS::StackName"
      Subnets: !Split [",", 'Fn::ImportValue': !Sub "${VPCStackName}-PublicSubnetIds"]

      SecurityGroups:
        - !Ref AlbSecurityGroup
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}"

  AlbListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: AlbTargetGroup
      LoadBalancerArn: !Ref Alb
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref SSLCertificateArn

  AlbTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /pulse
      HealthCheckProtocol: HTTP
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 3
      TargetType: ip
      Protocol: HTTP
      Port: 80
      VpcId: { 'Fn::ImportValue': !Sub "${VPCStackName}-VpcId" }

      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}"

  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: !Sub "${AWS::StackName} alb security group"
      GroupName: !Sub "${AWS::StackName}-alb"
      SecurityGroupEgress: 
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        DestinationSecurityGroupId: !Ref "EcsSecurityGroup"
      SecurityGroupIngress: 
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-alb"
      VpcId: { 'Fn::ImportValue': !Sub "${VPCStackName}-VpcId" }

  EcsTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ContainerDefinitions:
        - Name: nginx
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EcsNginxRepositoryName}:${EcsNginxGitSHA}"
          Essential: true
          HealthCheck:
            Command: 
              - CMD-SHELL
              - curl -f http://127.0.0.1/pulse || exit 1
            Interval: 30
            Retries: 3
            Timeout: 5
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub '/ecs/${AWS::StackName}/nginx'
              awslogs-region: us-east-1
              awslogs-stream-prefix: ecs
          PortMappings:
            - Protocol: tcp
              ContainerPort: 80
          Ulimits:
            - Name: nofile
              SoftLimit: 16384
              HardLimit: 16384

        - Name: proxy
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EcsProxyRepositoryName}:${EcsProxyGitSHA}"
          Essential: true
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://127.0.0.1:8000/pulse || exit 1
            Interval: 30
            Retries: 3
            Timeout: 5
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub '/ecs/${AWS::StackName}/proxy'
              awslogs-region: us-east-1
              awslogs-stream-prefix: ecs
              awslogs-datetime-format: '\[%Y-%m-%d %H:%M:%S %z\]'
          Environment:
            - Name: APP_ENV
              Value: !Ref EcsAppEnv
            - Name: GEOIP_S3_BUCKET
              Value: !Ref EcsAppGeoipS3Bucket
            - Name: ADZERK_SECRET_NAME
              Value: !Ref EcsAppAdzerkSecretName
            - Name: SENTRY_DSN_SECRET_NAME
              Value: !Ref EcsAppSentryDsnSecretName
          PortMappings:
            - Protocol: tcp
              ContainerPort: 8000
          Ulimits:
            - Name: nofile
              SoftLimit: 16384
              HardLimit: 16384

      Cpu: !Ref EcsTaskCpu
      Memory: !Ref EcsTaskMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Family: !Sub "${AWS::StackName}"
      ExecutionRoleArn: !GetAtt EcsTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt EcsTaskRole.Arn

  EcsService:
    Type: 'AWS::ECS::Service'
    DependsOn: AlbListener
    Properties:
      Cluster: !Ref "EcsCluster"
      LaunchType: FARGATE
      DesiredCount: !Ref "EcsServiceTaskDesiredCount"
      LoadBalancers:
        - ContainerPort: 80
          ContainerName: nginx
          TargetGroupArn: !Ref "AlbTargetGroup"
      TaskDefinition: !Ref "EcsTaskDefinition"
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref "EcsSecurityGroup"
          Subnets: !Split [",", 'Fn::ImportValue': !Join ["-", [ !Ref VPCStackName, 'PrivateSubnetIds' ]]]

  EcsCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref AWS::StackName
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}"

  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}ExecutionRole"
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}TaskRole"
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${AWS::StackName}TaskPolicy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub "arn:aws:s3:::${EcsAppGeoipS3Bucket}"
                  - !Sub "arn:aws:s3:::${EcsAppGeoipS3Bucket}/*"
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${EcsAppAdzerkSecretName}-??????"
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${EcsAppSentryDsnSecretName}-??????"

  EcsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${AWS::StackName} ecs security group"
      GroupName: !Sub "${AWS::StackName}-ecs"
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-ecs"
      VpcId: { 'Fn::ImportValue': !Sub "${VPCStackName}-VpcId" }


  EcsSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EcsSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      SourceSecurityGroupId: !Ref "AlbSecurityGroup"

  EcsAutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-AutoScalingRole"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: application-autoscaling.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-AutoScalingPolicy"
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - application-autoscaling:*
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:PutMetricAlarm
                  - ecs:DescribeServices
                  - ecs:UpdateService
                Resource:
                  - !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:service/${AWS::StackName}-*"
                  - !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${AWS::StackName}:*"
                  - !Sub "arn:aws:cloudwatch:${AWS::Region}:${AWS::AccountId}:alarm:${AWS::StackName}-*"

  ServiceScalingTarget:
    Type: "AWS::ApplicationAutoScaling::ScalableTarget"
    Properties:
      MinCapacity: !Ref "EcsServiceTaskMinCount"
      MaxCapacity: !Ref "EcsServiceTaskMaxCount"
      ResourceId: !Sub
        - "service/${EcsClusterName}/${EcsServiceName}"
        - EcsClusterName: !Ref "EcsCluster"
          EcsServiceName: !GetAtt EcsService.Name
      RoleARN: !GetAtt EcsAutoScalingRole.Arn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  ServiceScaleUpPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: ScaleOutPolicy
      PolicyType: StepScaling
      ScalingTargetId: !Ref ServiceScalingTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: !Ref EcsScaleTaskUpCooldown
        MetricAggregationType: Average
        StepAdjustments:
          - ScalingAdjustment: !Ref EcsScaleTaskUpCount
            MetricIntervalLowerBound: 0

  ServiceScaleDownPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: ScaleInPolicy
      PolicyType: StepScaling
      ScalingTargetId: !Ref ServiceScalingTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: !Ref EcsScaleTaskDownCooldown
        MetricAggregationType: Average
        StepAdjustments:
          - ScalingAdjustment: !Ref EcsScaleTaskDownCount
            MetricIntervalUpperBound: 0

  ServiceCPUScaleUpAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: !Ref ServiceScaleEvaluationPeriods
      Statistic: Average
      TreatMissingData: breaching
      Threshold: !Ref ServiceCpuScaleUpThreshold
      AlarmDescription: Alarm to add capacity if CPU is high
      Period: 60
      AlarmActions:
        - !Ref ServiceScaleUpPolicy
      Namespace: AWS/ECS
      Dimensions:
        - Name: ClusterName
          Value: !Ref "EcsCluster"
        - Name: ServiceName
          Value: !GetAtt EcsService.Name
      ComparisonOperator: GreaterThanThreshold
      MetricName: CPUUtilization

  ServiceCPUScaleDownAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: !Ref ServiceScaleEvaluationPeriods
      Statistic: Average
      TreatMissingData: breaching
      Threshold: !Ref ServiceCpuScaleDownThreshold
      AlarmDescription: Alarm to reduce capacity if container CPU is low
      Period: 300
      AlarmActions:
        - !Ref ServiceScaleDownPolicy
      Namespace: AWS/ECS
      Dimensions:
        - Name: ClusterName
          Value: !Ref "EcsCluster"
        - Name: ServiceName
          Value: !GetAtt EcsService.Name
      ComparisonOperator: LessThanThreshold
      MetricName: CPUUtilization

