# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
#
version: 2.1

jobs:
  tests_unit:
    docker:
      - image: cimg/python:3.11
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/proxy-server
    parameters:
      pipenv_path:
        default: "./"
        type: string
    environment:
      WORKON_HOME: '~/.venv'
    steps:
      - checkout

      - restore_cache:
          key: deps-test-{{ checksum "<<parameters.pipenv_path>>Pipfile.lock" }}-v1
      - run:
          name: Build environment and install requirements
          command: |
            pip install pipenv
            pipenv install --dev
      - save_cache:
          key: deps-test-{{ checksum "<<parameters.pipenv_path>>Pipfile.lock" }}-v1
          paths:
            - "~/.venv"

      - run:
          name: Run tests
          environment:
            APP_ENV: test
          command: |
            mkdir test-reports/
            pipenv run pytest tests/unit/ --cov=. --cov-config=.proxy_coveragerc --junitxml=test-reports/junit.xml
            pipenv run coverage html --rcfile=.proxy_coveragerc

      # test reporting and pylint are still WIP
      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: proxy-server-coverage


# Workflow shortcuts
workflows:
  version: 2
  build_and_test:
    jobs:
      - tests_unit:
          context: pocket-proxy
