# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  tests_unit:
    docker:
      - image: circleci/python:3.7.4

    working_directory: ~/proxy-server

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pip.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r pip.lock
            pip install -r requirements.dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "pip.lock" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            mkdir test-reports/
            pytest tests/unit/ --cov=. --cov-config=.proxy_coveragerc --junitxml=test-reports/junit.xml
            coverage html --rcfile=.proxy_coveragerc

      # test reporting and pylint are still WIP
      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: proxy-server-coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - tests_unit
